disableUpdateCheck: false
unDisguiseIfInOwnTerritory: false
unDisguiseIfInEnemyTerritory: false
leadersCanSetWarps: true
officersCanSetWarps: true
membersCanSetWarps: false
warpSetting: 1
maxWarps: 5
mustBeInOwnTerritoryToCreate: true
warpTeleportAllowedFromEnemyTerritory: true
warpTeleportAllowedFromDifferentWorld: true
warpTeleportAllowedEnemyDistance: 35
warpTeleportIgnoreEnemiesIfInOwnTerritory: true
smokeEffectOnWarp: true
powerBoostIfPeaceful: 0
leadersCanSetJails: true
officersCanSetJails: true
leadersCanSetRules: true
officersCanSetRules: true
maxRulesPerFaction: 12
membersCanSetJails: false
leadersCanJail: true
officersCanJail: true
leadersCanAnnounce: true
officersCanAnnounce: true
showLastAnnounceOnLogin: true
showLastAnnounceOnLandEnter: true
leadersCanFactionBan: true
officersCanFactionBan: true
leadersCanFactionUnban: true
officersCanFactionUnban: true
leaderCanNotBeBanned: true
leadersCanToggleState: false
officersCanToggleState: false
membersCanToggleState: false
extraPowerLossIfDeathByOther: 0.0
extraPowerWhenKillPlayer: 0.0
extraPowerLossIfDeathBySuicide: 0.0
extraPowerLossIfDeathByPVP: 0.0
extraPowerLossIfDeathByMob: 0.0
extraPowerLossIfDeathByCactus: 0.0
extraPowerLossIfDeathByTNT: 0.0
extraPowerLossIfDeathByFire: 0.0
extraPowerLossIfDeathByPotion: 0.0
enablePermissionGroups: false
economy_enable: false
economy_costToWarp: 0
economy_costToCreateWarp: 0
economy_costToDeleteWarp: 0
economy_costToAnnounce: 0
economy_costToJail: 0
economy_costToSetJail: 0
economy_costToUnJail: 0
economy_costToToggleUpPeaceful: 0
economy_costToToggleDownPeaceful: 0
useLWCIntegrationFix: false
DoNotChangeMe: 8
